Initial version of my intro to async programming with Dancer2
PerlDancer/advent-calendar pull request #69
Opened 2020-12-19 15:55 UTC by xsawyerx

The second part will be on promises

2020-12-19 16:19 UTC, GeekRuthie commented
Sawyer, this is awesome! Async has always been kind of black-boxy and mysterious to me, but you've opened it up and made sense of it.  Great article!

2020-12-19 22:15 UTC, cromedome requested changes
A couple of minor typos, and that's it! This is a great example of async - easy to follow, and I like how you layer more functionality on as the example progresses.

Really looking forward to part 2!

2020-12-19 22:15 UTC, cromedome commented on danceradvent/public/articles/2020/21-asynchronous-intro.pm
> +=head2 So what example are w using here?
*we using

2020-12-20 10:47 UTC, xsawyerx commented on danceradvent/public/articles/2020/21-asynchronous-intro.pm
> +L<this article|https://advent.perldancer.org/2020>
Fixed in latest commit.

2020-12-20 10:48 UTC, xsawyerx commented on danceradvent/public/articles/2020/21-asynchronous-intro.pm
> +=head2 So what example are w using here?
Fixed in latest commit.

2020-12-20 11:17 UTC, racke commented on danceradvent/public/articles/2020/21-asynchronous-intro.pod
> +The subroutine calling C<< $cv-&gt;end >> notes the end of the async
Github renders that to `$cv-&gt;end`.

2020-12-20 11:19 UTC, racke commented on danceradvent/public/articles/2020/21-asynchronous-intro.pod
> +    use experimental qw< postderef signatures >;
It might be less confusing if your explicitly require the Perl version where this isn't experimental.

2020-12-20 16:45 UTC, cromedome commented on danceradvent/public/articles/2020/21-asynchronous-intro.pod
> +The subroutine calling C<< $cv-&gt;end >> notes the end of the async
:+1: - thanks for spotting that @racke

2020-12-20 16:48 UTC, cromedome requested changes
The adjustments you made to this really polished this up. I second the pod fix that @racke noticed. 

I moved his article up one day so we can put this and part 2 on back to back days, FYI.

2020-12-21 03:20 UTC, merged